### ISSUE TITLE
Blocks players from chatting on the IRC server.

### ISSUE THREAD

**Issue by DI3HARD139** [Zippy1/ls_commands#1]
In-game chat not relaying to IRC. Server can relay the "*** <name> has joined the game" and "*** <name> has left the game" however.

**Comment by luk3yx** [comment]
Would that pull request work?

**Comment by Zippy1** [comment]
strange
it might be the mute part, I'll try to fix it

**Comment by luk3yx** [comment]
Can someone please close this issue? It's been fixed with pull request #2.

**Comment by luk3yx** [comment]
Thanks.
